services:
  # Spring Boot Backend Service
  - type: web
    name: ems-backend
    env: java
    rootDir: ems-backend
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/ems-backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - fromGroup: ems-database-credentials

  # React Frontend Service
  - type: static_site
    name: ems-frontend
    rootDir: ems-frontend
    buildCommand: "npm run build"
    # This path is now corrected to be from the repository root
    publishDir: "ems-frontend/build"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html